language: scala
scala:
   - 2.13.0
   - 2.12.10

script:
  - sbt clean coverage test coverageReport 
  - if [[ "$TRAVIS_SCALA_VERSION" != 2.13.* ]];
    then
#      sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite;
      sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov;
    else 
      echo "Skipping code coverage reporting and docs on 2.13";
    fi  

install:
  - pip install --user codecov

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jdk:
  - oraclejdk9
  - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)  
